logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 9999

spring:
  application:
    name: gateway-nacos-test

  #配置nacos注册中心
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 121.199.72.238:8848

   # 配置断言 简单请求转发 相当于请求/provider-test/**路径的请求  会全部路由到 http://localhost:8000
   # 例如 http://localhost:9999/provider-test/discovery/one --> http://localhost:8000/provider-test/discovery/one
    gateway:
      routes:
        - id: provider-test-one
          uri: http://localhost:8000
          predicates:
          - Path=/provider-test/**

