logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 9999

spring:
  application:
    name: gateway-main

  #配置nacos注册中心
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 121.199.72.238:8848

# 配置断言 简单请求转发,即将 网络请求的转发规则
# 这种相当于直接将符合/provider-test/** 的请求 路由到固定地址 http://localhost:8001 上,例如可以用于本地调试
#    gateway:
#      routes:
#        - id: provider-test-one
#          uri: http://localhost:8001
#          predicates:
#          - Path=/provider-test/**

#  LB模式,即是负载均衡模式,即将/provider-test/**格式的数据,路由到 注册中心nacos 名称为
#   nacos-main的集群机器中,负载均衡模式（尤其的需要注意nacos的服务名遵守一定的服务规则,否则会失效）
    gateway:
      routes:
        - id: provider-test-one
          uri: lb://nacos-main
          predicates:
            - Path=/provider-test/**

