server:
  port: 8001

spring:
  application:
    name: nacos-main

  #配置nacos注册中心
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 121.199.72.238:8848

